"""add product access tracking for cache eviction

Revision ID: c8b07102234a
Revises: a613b2182ee2
Create Date: 2026-08-04 17:38:46.476829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8b07102234a'
down_revision: Union[str, Sequence[str], None] = 'a613b2182ee2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('product', sa.Column('access_count', sa.Integer(), server_default='0', nullable=False))
    op.create_index('ix_product_access_count_last_accessed', 'product', ['access_count', 'last_accessed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_product_access_count_last_accessed', table_name='product')
    op.drop_column('product', 'access_count')
    op.drop_column('product', 'last_accessed_at')
    # ### end Alembic commands ###
