"""add listing availability tracking

Revision ID: b566f1f1279b
Revises: c8b07102234a
Create Date: 2026-08-22 16:53:43.250084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b566f1f1279b'
down_revision: Union[str, Sequence[str], None] = 'c8b07102234a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listing', sa.Column('unavailable_since', sa.DateTime(timezone=True), nullable=True))
    # Indice para el filtro que corre en CADA busqueda: "solo las que se pueden comprar".
    op.create_index(
        "ix_listing_unavailable_since",
        "listing",
        ["unavailable_since"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listing', 'unavailable_since')
    op.drop_index("ix_listing_unavailable_since", table_name="listing")
    # ### end Alembic commands ###
